#!/usr/bin/env node
import express from 'express';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, watch } from 'fs';
import { join, dirname, extname, basename } from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';
import { runScript, getScriptArgs } from './scripts/run-pipeline.mjs';
import { loadProjectEnv } from './load-project-env.mjs';
import { estimateJobScore } from './job-score-heuristic.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
await loadProjectEnv(ROOT);

const app = express();
const PORT = 3000;

const PATHS = {
  pipeline: join(ROOT, 'data', 'pipeline.md'),
  applications: join(ROOT, 'data', 'applications.md'),
  scanHistory: join(ROOT, 'data', 'scan-history.tsv'),
  output: join(ROOT, 'output'),
  reports: join(ROOT, 'reports'),
  profile: join(ROOT, 'config', 'profile.yml'),
  ui: join(ROOT, 'dashboard-ui.html'),
};

/** CV PDFs/HTML live under output/; ollama-html can have thousands of tailored pages — do not scan for resume list. */
const OUTPUT_RESUME_LIST_OPTS = { skipDirs: new Set(['ollama-html']) };

app.use(express.json());

let runningScript = null;
const updateClients = new Set();

function safeRead(path, fallback = '') {
  if (!existsSync(path)) return fallback;
  return readFileSync(path, 'utf-8');
}

function slug(v) {
  return String(v || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function normalizeUrlForReportMatch(u) {
  return String(u || '')
    .trim()
    .replace(/\/+$/, '');
}

/**
 * When applications.md has no Report link, find evaluation markdown: filename slugs
 * (company + title), else newest report whose body contains the pipeline job URL.
 */
function resolveReportSnapshotForJob(job) {
  if (!existsSync(PATHS.reports) || !job?.url) return null;
  const names = readdirSync(PATHS.reports).filter((f) => f.toLowerCase().endsWith('.md'));
  if (names.length === 0) return null;

  const c = slug(job.company);
  const r = slug(job.title || '');

  function pickNewest(filteredNames) {
    if (filteredNames.length === 0) return null;
    let best = null;
    let bestT = -1;
    for (const name of filteredNames) {
      const p = join(PATHS.reports, name);
      const t = statSync(p).mtimeMs;
      if (t > bestT) {
        bestT = t;
        best = name;
      }
    }
    return best;
  }

  const both = r ? names.filter((n) => slug(n).includes(c) && slug(n).includes(r)) : [];
  let picked = pickNewest(both);

  if (!picked) {
    const co = names.filter((n) => slug(n).includes(c));
    picked = pickNewest(co);
  }

  const needle = normalizeUrlForReportMatch(job.url);
  if (!picked && needle) {
    const headBytes = 96 * 1024;
    let bestName = null;
    let bestT = -1;
    for (const name of names) {
      const p = join(PATHS.reports, name);
      let frag;
      try {
        const buf = readFileSync(p);
        frag = buf.length > headBytes ? buf.subarray(0, headBytes).toString('utf8') : buf.toString('utf8');
      } catch {
        continue;
      }
      if (!frag.includes(needle)) continue;
      const t = statSync(p).mtimeMs;
      if (t > bestT) {
        bestT = t;
        bestName = name;
      }
    }
    picked = bestName;
  }

  if (!picked) return null;
  try {
    const markdown = readFileSync(join(PATHS.reports, picked), 'utf-8');
    return { filename: picked, markdown };
  } catch {
    return null;
  }
}

/** Short excerpt from cv.md Professional Summary for report preview when no reports/*.md exists. */
function extractCvSummaryExcerpt(maxLen = 900) {
  const p = join(ROOT, 'cv.md');
  if (!existsSync(p)) return '';
  const cv = safeRead(p, '');
  const m = cv.match(/^##\s+Professional Summary\s*\n([\s\S]*?)(?=^##\s|\Z)/im);
  if (!m) return '';
  return m[1].trim().replace(/\s+/g, ' ').slice(0, maxLen);
}

/**
 * Always-on markdown for View report when no evaluation file exists yet.
 * Matches career-ops report header shape enough to be useful (not a full A–G LLM run).
 */
function buildPlaceholderEvaluationMarkdown(job) {
  const escCell = (s) =>
    String(s ?? '')
      .replace(/\|/g, '/')
      .replace(/\r?\n/g, ' ')
      .trim();
  const today = new Date().toISOString().slice(0, 10);
  const cvExcerpt = extractCvSummaryExcerpt(1000);
  const tracker = job.hasTrackerRow ? 'Yes (see data/applications.md)' : 'No matching tracker row for this company + title';

  return `# Evaluation — ${job.company} — ${job.title}

**Date:** ${today}
**Pipeline #:** ${job.id}
**URL:** ${job.url || '—'}
**Score:** ${job.score || '—/5'} *(from applications tracker, linked report, or title heuristic — not a fresh LLM evaluation)*
**Legitimacy:** not evaluated yet
**PDF:** unknown
**Report file:** *(none on disk — this preview is generated by the dashboard)*

---

## A. Role summary (placeholder)

No saved evaluation yet. Run **Evaluate Pipeline** for this row or use \`/career-ops oferta\` with the job URL so career-ops can write a full report to \`reports/\` (blocks A–G per \`modes/oferta.md\`).

## B. CV match (placeholder)

Pending JD analysis. When you evaluate, the report will map posting requirements to bullets in \`cv.md\`.

## C–G. Level, comp, personalization, interview, legitimacy

*Pending — generated after first evaluation.*

---

## Pipeline context (live)

| Field | Value |
|-------|--------|
| Status | ${escCell(job.status || 'pending')} |
| Score shown in UI | ${escCell(job.score || '—/5')} |
| First seen (scan) | ${escCell(job.dateAdded || '—')} |
| Tracker row | ${escCell(tracker)} |
| Report link in tracker | ${job.reportHint ? escCell(String(job.reportHint).slice(0, 200)) + (String(job.reportHint).length > 200 ? '…' : '') : '—'} |

## Your profile (from cv.md)

${cvExcerpt ? `${cvExcerpt}${cvExcerpt.length >= 1000 ? '…' : ''}` : '*Add or expand `## Professional Summary` in cv.md for a snippet here.*'}

## Next actions

1. **Evaluate** — Dashboard button or \`node evaluate-pipeline.mjs\` / chat \`/career-ops oferta\` with this URL.
2. **Link report** — After a report exists under \`reports/\`, add \`[###](reports/###-slug-YYYY-MM-DD.md)\` in the applications tracker **Report** column for this role.
3. **View report** will then load the saved file; until then, this preview refreshes whenever you open it.

**Sources:** dashboard auto-preview (pipeline + cv.md excerpt only). Not scraped JD text or LLM output.
`;
}

/** Checkbox marks in data/pipeline.md (single character inside [...]). */
function markToPipelineStatus(mark) {
  const m = String(mark || '').trim();
  if (!m) return 'pending';
  switch (m) {
    case 'x':
      return 'evaluated';
    case '!':
      return 'interviewing';
    case 'a':
      return 'applied';
    case 'r':
      return 'rejected';
    case 'o':
      return 'offer';
    default:
      return 'pending';
  }
}

/** Inverse: dashboard status → one character for markdown checkbox line. */
function pipelineStatusToMark(nextStatus) {
  const s = String(nextStatus || 'pending').toLowerCase();
  if (s === 'pending') return ' ';
  if (s === 'evaluated') return 'x';
  if (s === 'interviewing') return '!';
  if (s === 'applied') return 'a';
  if (s === 'rejected') return 'r';
  if (s === 'offer') return 'o';
  return 'x';
}

/** applications.md status column uses canonical labels (see templates/states.yml). */
function dashboardStatusToCanonical(dashboardStatus) {
  const s = String(dashboardStatus || '').toLowerCase();
  if (s === 'pending') return null;
  const map = {
    evaluated: 'Evaluated',
    applied: 'Applied',
    interviewing: 'Interview',
    rejected: 'Rejected',
    offer: 'Offer',
  };
  return map[s] ?? null;
}

function parsePipeline() {
  const text = safeRead(PATHS.pipeline, '');
  const rows = [];
  const lineRows = text.split(/\r?\n/);

  let id = 1;
  for (const line of lineRows) {
    const m = line.match(/^\s*-\s*\[([^\]]*)\]\s+(https?:\/\/\S+)\s*\|\s*([^|]+)\s*\|\s*(.+)\s*$/i);
    if (!m) continue;
    const status = markToPipelineStatus(m[1]);
    rows.push({
      id: id++,
      source: 'checkbox',
      line,
      status,
      url: m[2].trim(),
      company: m[3].trim(),
      title: m[4].trim(),
    });
  }

  if (rows.length > 0) return rows;

  // Table fallback
  for (const line of lineRows) {
    if (!line.trim().startsWith('|')) continue;
    if (/^\|\s*-+/.test(line) || /title/i.test(line)) continue;
    const cells = line.split('|').map((x) => x.trim()).filter(Boolean);
    if (cells.length < 4) continue;
    rows.push({
      id: id++,
      source: 'table',
      line,
      title: cells[0],
      company: cells[1],
      url: cells[2],
      status: (cells[3] || 'pending').toLowerCase(),
    });
  }
  return rows;
}

function parseApplications() {
  const text = safeRead(PATHS.applications, '');
  const rows = [];
  let id = 1;
  for (const line of text.split(/\r?\n/)) {
    if (!line.startsWith('|')) continue;
    if (line.includes('|---') || /\|\s*#\s*\|/.test(line)) continue;
    const c = line.split('|').map((x) => x.trim()).slice(1, -1);
    if (c.length < 9) continue;
    rows.push({
      id: id++,
      num: c[0],
      date: c[1],
      company: c[2],
      role: c[3],
      score: c[4],
      status: String(c[5] || 'Pending').toLowerCase(),
      pdf: c[6],
      report: c[7],
      notes: c[8] || '',
      line,
    });
  }
  return rows;
}

function parseScanHistory() {
  const text = safeRead(PATHS.scanHistory, '');
  const lines = text.split(/\r?\n/).filter(Boolean);
  const rows = [];
  for (const line of lines.slice(1)) {
    const [url, first_seen, portal, title, company, status] = line.split('\t');
    if (!url) continue;
    rows.push({ url, first_seen, portal, title, company, status });
  }
  return rows;
}

/**
 * @param {string} path
 * @param {string[]} exts
 * @param {string} [base]
 * @param {{ skipDirs?: Set<string> }} [options]
 */
function listFiles(path, exts, base = path, options = {}) {
  if (!existsSync(path)) return [];
  const skipDirs = options.skipDirs || new Set();
  const out = [];
  for (const f of readdirSync(path)) {
    const p = join(path, f);
    const s = statSync(p);
    if (s.isDirectory()) {
      if (skipDirs.has(f)) continue;
      out.push(...listFiles(p, exts, base, options));
      continue;
    }
    if (!exts.includes(extname(f).toLowerCase())) continue;
    const relPath = p.slice(base.length + 1).replaceAll('\\', '/');
    out.push({
      name: f,
      relPath,
      path: p,
      size: s.size,
      mtime: s.mtime.toISOString(),
    });
  }
  return out;
}

/** Align tracker wording with dashboard-ui.html `<select>` (canonical Interview → interviewing). */
function normalizeDashboardStatus(s) {
  const v = String(s || 'pending').toLowerCase();
  if (v === 'interview') return 'interviewing';
  return v;
}

/**
 * Pipeline inbox line is the source of truth for workflow state once it is not `[ ]`.
 * If the line is still pending, use applications.md (evaluated via /career-ops) for score/status.
 */
function mergedPipelineApplicationStatus(app, job) {
  const j = job?.status || 'pending';
  if (j !== 'pending') return j;
  return app?.status || 'pending';
}

function extractScoreFromReportText(md) {
  const text = String(md || '');
  const m =
    text.match(/\*\*Score:\*\*\s*([0-5](?:\.\d+)?)\s*\/\s*5/i) ||
    text.match(/\*\*Overall Score:\*\*\s*([0-5](?:\.\d+)?)\s*\/\s*5/i) ||
    text.match(/\bScore:\s*([0-5](?:\.\d+)?)\s*\/\s*5/i);
  if (!m) return null;
  return `${m[1]}/5`;
}

function reportScoreForJob(job, reportFiles) {
  if (!Array.isArray(reportFiles) || reportFiles.length === 0) return null;
  const companySlug = slug(job.company);
  const roleSlug = slug(job.title);
  const hit =
    reportFiles.find((r) => slug(r.name).includes(companySlug) && slug(r.name).includes(roleSlug)) ||
    reportFiles.find((r) => slug(r.name).includes(companySlug)) ||
    null;
  if (!hit) return null;
  const md = safeRead(hit.path, '');
  return extractScoreFromReportText(md);
}

function enrichJobs(jobs, options = {}) {
  const appRows = parseApplications();
  const histByUrl = new Map(parseScanHistory().map((h) => [h.url, h]));
  const reportFiles = listFiles(PATHS.reports, ['.md']);
  const autoScore = options.autoScore !== false;
  return jobs.map((job) => {
    const app = appRows.find((a) => slug(a.company) === slug(job.company) && slug(a.role) === slug(job.title));
    const hist = histByUrl.get(job.url);
    const raw = mergedPipelineApplicationStatus(app, job);
    const score = app?.score || reportScoreForJob(job, reportFiles) || (autoScore ? estimateJobScore(job.title) : '—/5');
    return {
      ...job,
      status: normalizeDashboardStatus(raw),
      score,
      dateAdded: hist?.first_seen || '—',
      reportHint: app?.report || '',
      hasTrackerRow: Boolean(app),
    };
  });
}

function stats() {
  const jobs = enrichJobs(parsePipeline());
  const resumes = listFiles(PATHS.output, ['.docx', '.pdf', '.html'], PATHS.output, OUTPUT_RESUME_LIST_OPTS);
  const reports = listFiles(PATHS.reports, ['.md']);
  const applied = jobs.filter((j) => /applied/.test(j.status)).length;
  const inProgress = jobs.filter((j) => /(interview|screen|progress)/.test(j.status)).length;
  return {
    pipelineTotal: jobs.length,
    applied,
    inProgress,
    resumesGenerated: resumes.length,
    evaluationsDone: reports.length,
    running: Boolean(runningScript),
    runningScript,
  };
}

function writePipelineStatus(id, nextStatus) {
  const text = safeRead(PATHS.pipeline, '');
  const lines = text.split(/\r?\n/);
  const jobs = parsePipeline();
  const job = jobs.find((j) => j.id === Number(id));
  if (!job) return false;

  if (job.source === 'checkbox') {
    const mark = pipelineStatusToMark(nextStatus);
    const bracket = mark === ' ' ? '[ ]' : `[${mark}]`;
    const nextLine = job.line.replace(/\[[^\]]*\]/, bracket);
    const idx = lines.findIndex((ln) => ln === job.line);
    if (idx >= 0) lines[idx] = nextLine;
  } else {
    const idx = lines.findIndex((ln) => ln === job.line);
    if (idx >= 0) {
      const cells = job.line.split('|').map((x) => x.trim()).filter(Boolean);
      if (cells.length >= 4) {
        lines[idx] = `| ${cells[0]} | ${cells[1]} | ${cells[2]} | ${nextStatus} |`;
      }
    }
  }
  writeFileSync(PATHS.pipeline, lines.join('\n'), 'utf-8');
  return true;
}

function writeApplicationStatus(id, nextStatus) {
  if (!existsSync(PATHS.applications)) return false;
  const text = safeRead(PATHS.applications, '');
  const lines = text.split(/\r?\n/);
  const apps = parseApplications();
  const appRow = apps.find((a) => a.id === Number(id));
  if (!appRow) return false;
  const idx = lines.findIndex((ln) => ln === appRow.line);
  if (idx < 0) return false;
  const c = appRow.line.split('|').map((x) => x.trim()).slice(1, -1);
  if (c.length < 9) return false;
  c[5] = nextStatus;
  lines[idx] = `| ${c.join(' | ')} |`;
  writeFileSync(PATHS.applications, lines.join('\n'), 'utf-8');
  return true;
}

function escTableCell(s) {
  return String(s || '')
    .replace(/\|/g, '/')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function findDuplicatePipelineJob(url, company, title) {
  const jobs = parsePipeline();
  const u = url.trim();
  const sc = slug(company);
  const st = slug(title);
  return jobs.find((j) => j.url === u || (slug(j.company) === sc && slug(j.title) === st));
}

const APPLICATIONS_TEMPLATE = `# Applications Tracker

| # | Date | Company | Role | Score | Status | PDF | Report | Notes |
|---|------|---------|------|-------|--------|-----|--------|-------|
`;

function ensureApplicationsFile() {
  if (!existsSync(PATHS.applications)) {
    writeFileSync(PATHS.applications, APPLICATIONS_TEMPLATE, 'utf-8');
  }
}

function nextApplicationNumber() {
  const apps = parseApplications();
  let max = 0;
  for (const a of apps) {
    const n = parseInt(String(a.num).replace(/\D/g, ''), 10);
    if (!Number.isNaN(n)) max = Math.max(max, n);
  }
  return String(max + 1).padStart(3, '0');
}

/** Append one checkbox line under ## Pendientes (same strategy as scan.mjs). */
function insertPipelineLine(newLine) {
  const marker = '## Pendientes';
  let text = safeRead(PATHS.pipeline, '');
  if (!text.trim()) {
    text = `# Pipeline — job URL inbox\n\n${marker}\n\n`;
  }
  const idx = text.indexOf(marker);
  if (idx === -1) {
    const procIdx = text.indexOf('## Procesadas');
    const insertAt = procIdx === -1 ? text.length : procIdx;
    text = `${text.slice(0, insertAt)}\n${marker}\n\n${newLine}\n\n${text.slice(insertAt)}`;
  } else {
    const afterMarker = idx + marker.length;
    const nextSection = text.indexOf('\n## ', afterMarker);
    const insertAt = nextSection === -1 ? text.length : nextSection;
    text = `${text.slice(0, insertAt)}\n${newLine}\n${text.slice(insertAt)}`;
  }
  writeFileSync(PATHS.pipeline, text, 'utf-8');
}

/** Append a tracker row for dashboard-added jobs (canonical status only). */
function appendApplicationLine(company, title, dashboardStatus) {
  const canonical = dashboardStatusToCanonical(dashboardStatus);
  if (!canonical) return false;
  ensureApplicationsFile();
  const num = nextApplicationNumber();
  const date = new Date().toISOString().slice(0, 10);
  const co = escTableCell(company);
  const ro = escTableCell(title);
  const row = `| ${num} | ${date} | ${co} | ${ro} | —/5 | ${canonical} | ❌ | — | Added via dashboard |`;
  const text = safeRead(PATHS.applications, '');
  const out = text.replace(/\s*$/, '') + `\n${row}\n`;
  writeFileSync(PATHS.applications, out, 'utf-8');
  return true;
}

/** Match tracker row by company + role (same slugs as enrichJobs) and set canonical status. */
function writeApplicationStatusForJob(job, dashboardStatus) {
  if (!existsSync(PATHS.applications) || !job) return false;
  const canonical = dashboardStatusToCanonical(dashboardStatus);
  if (!canonical) return false;
  const text = safeRead(PATHS.applications, '');
  const lines = text.split(/\r?\n/);
  const apps = parseApplications();
  const appRow = apps.find((a) => slug(a.company) === slug(job.company) && slug(a.role) === slug(job.title));
  if (!appRow) return false;
  const idx = lines.findIndex((ln) => ln === appRow.line);
  if (idx < 0) return false;
  const c = appRow.line.split('|').map((x) => x.trim()).slice(1, -1);
  if (c.length < 9) return false;
  c[5] = canonical;
  lines[idx] = `| ${c.join(' | ')} |`;
  writeFileSync(PATHS.applications, lines.join('\n'), 'utf-8');
  return true;
}

function sendSse(res, event, payload) {
  res.write(`event: ${event}\n`);
  res.write(`data: ${JSON.stringify(payload)}\n\n`);
}

function broadcastUpdate(kind) {
  for (const client of updateClients) {
    sendSse(client, 'refresh', { kind, at: new Date().toISOString() });
  }
}

app.get('/', (_req, res) => res.sendFile(PATHS.ui));
app.get('/dashboard-ui.html', (_req, res) => res.sendFile(PATHS.ui));

app.get('/api/stats', (_req, res) => res.json(stats()));
app.get('/api/jobs', (req, res) => {
  const autoScore = String(req.query.autoScore || '1') !== '0';
  res.json(enrichJobs(parsePipeline(), { autoScore }));
});

/**
 * Add a job URL to data/pipeline.md (and optionally data/applications.md).
 * Body: { url, company, title, status?, addToApplications? }
 * status: pending | evaluated | applied | interviewing | rejected | offer (default applied for "already applied")
 */
app.post('/api/jobs', (req, res) => {
  const url = String(req.body.url || '').trim();
  const company = escTableCell(req.body.company);
  const title = escTableCell(req.body.title);
  const status = String(req.body.status || 'applied').toLowerCase();
  const addToApplications = req.body.addToApplications !== false;

  try {
    void new URL(url);
  } catch {
    return res.status(400).json({ ok: false, error: 'Invalid URL (must start with http/https)' });
  }
  if (!company || !title) {
    return res.status(400).json({ ok: false, error: 'Company and job title are required' });
  }

  const dup = findDuplicatePipelineJob(url, company, title);
  if (dup) {
    return res.status(409).json({ ok: false, error: 'This URL or company+title is already in the pipeline', id: dup.id });
  }

  const mark = pipelineStatusToMark(status);
  const bracket = mark === ' ' ? '[ ]' : `[${mark}]`;
  const newLine = `- ${bracket} ${url} | ${company} | ${title}`;
  insertPipelineLine(newLine);

  let trackerRow = false;
  let trackerNote = null;
  if (addToApplications) {
    if (dashboardStatusToCanonical(status)) {
      trackerRow = appendApplicationLine(company, title, status);
    } else {
      trackerNote =
        'Tracker row was not created: pick a workflow status (e.g. applied, evaluated) or turn off “Add row to applications tracker”.';
    }
  }

  broadcastUpdate('pipeline');
  if (trackerRow) broadcastUpdate('applications');
  res.json({ ok: true, trackerRow, trackerNote });
});
app.get('/api/resumes', (_req, res) => {
  const list = listFiles(PATHS.output, ['.docx', '.pdf', '.html'], PATHS.output, OUTPUT_RESUME_LIST_OPTS);
  list.sort((a, b) => new Date(b.mtime) - new Date(a.mtime));
  res.json(list);
});
app.get('/api/reports', (_req, res) => res.json(listFiles(PATHS.reports, ['.md'])));
/**
 * View report: real reports/*.md when matched; otherwise always return placeholder markdown
 * so every pipeline job id has readable content (including newly added rows).
 */
app.get('/api/job/:id/report', (req, res) => {
  const id = Number(req.params.id);
  const jobs = enrichJobs(parsePipeline());
  const job = jobs.find((j) => j.id === id);
  if (!job) return res.status(404).json({ error: 'Pipeline job not found' });
  const resolved = resolveReportSnapshotForJob(job);
  if (resolved) {
    return res.json({
      filename: resolved.filename,
      markdown: resolved.markdown,
      matched: true,
      placeholder: false,
    });
  }
  const markdown = buildPlaceholderEvaluationMarkdown(job);
  res.json({
    filename: null,
    markdown,
    matched: false,
    placeholder: true,
  });
});
app.get('/api/history', (_req, res) => {
  const lines = safeRead(PATHS.scanHistory, '').split(/\r?\n/).filter(Boolean);
  res.json(lines.slice(-50));
});

app.get('/api/report/:filename', (req, res) => {
  const p = join(PATHS.reports, basename(req.params.filename));
  if (!existsSync(p)) return res.status(404).json({ error: 'Report not found' });
  res.type('text/plain').send(readFileSync(p, 'utf-8'));
});

app.get('/api/resume/:filename', (req, res) => {
  const p = join(PATHS.output, basename(req.params.filename));
  if (!existsSync(p)) return res.status(404).json({ error: 'Resume not found' });
  res.download(p);
});

app.get('/api/resume', (req, res) => {
  const rel = String(req.query.path || '').replaceAll('\\', '/').replace(/^\/+/, '');
  if (!rel) return res.status(400).json({ error: 'Missing path query param' });
  const p = join(PATHS.output, rel);
  if (!existsSync(p)) return res.status(404).json({ error: 'Resume not found' });
  res.download(p);
});

app.post('/api/job/:id/status', (req, res) => {
  const next = String(req.body.status || 'pending').toLowerCase();
  const jobs = parsePipeline();
  const job = jobs.find((j) => j.id === Number(req.params.id));
  const okPipeline = writePipelineStatus(req.params.id, next);
  if (!okPipeline) return res.status(404).json({ ok: false });
  writeApplicationStatusForJob(job, next);
  broadcastUpdate('pipeline');
  res.json({ ok: true });
});

app.post('/api/application/:id/status', (req, res) => {
  const ok = writeApplicationStatus(req.params.id, String(req.body.status || 'pending').toLowerCase());
  if (!ok) return res.status(404).json({ ok: false });
  broadcastUpdate('applications');
  res.json({ ok: true });
});

app.get('/api/config', (_req, res) => {
  const cfg = existsSync(PATHS.profile) ? yaml.load(readFileSync(PATHS.profile, 'utf-8')) : {};
  const history = parseScanHistory();
  res.json({
    targetRoles: cfg?.target_roles || {},
    location: cfg?.location || {},
    industries: cfg?.job_search_preferences?.company_types || [],
    lastScan: history.at(-1)?.first_seen || null,
    rapidApiKey: Boolean(process.env.RAPIDAPI_KEY),
    geminiApiKey: Boolean(process.env.GEMINI_API_KEY),
  });
});

app.get('/api/updates', (_req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders?.();
  updateClients.add(res);
  sendSse(res, 'ready', { ok: true });
  _req.on('close', () => updateClients.delete(res));
});

app.get('/api/run/:script', (req, res) => {
  const name = req.params.script;
  if (!getScriptArgs(name, req.query)) {
    return res.status(400).json({ error: 'Unknown script' });
  }

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders?.();

  if (runningScript) {
    sendSse(res, 'error', { line: `Another script is running: ${runningScript}` });
    sendSse(res, 'done', { ok: false, code: 1 });
    return res.end();
  }

  runningScript = name;
  const spec = getScriptArgs(name, req.query);
  const cmdPreview = spec ? `${spec.cmd} ${spec.args.join(' ')}` : name;
  sendSse(res, 'data', { line: `Starting ${name}...` });
  sendSse(res, 'data', { line: `Command: ${cmdPreview}` });

  let child;
  try {
    child = runScript(name, (event, line) => sendSse(res, event, { ts: new Date().toISOString(), line }), req.query);
  } catch (err) {
    runningScript = null;
    sendSse(res, 'error', { line: err.message });
    sendSse(res, 'done', { ok: false, code: 1 });
    return res.end();
  }

  child.on('close', (code) => {
    sendSse(res, 'done', { ok: code === 0, code });
    runningScript = null;
    broadcastUpdate('all');
    res.end();
  });

  req.on('close', () => {
    if (runningScript === name && child && !child.killed) {
      child.kill();
      runningScript = null;
    }
  });
});

for (const [kind, path, opts] of [
  ['pipeline', PATHS.pipeline, { recursive: false }],
  ['applications', PATHS.applications, { recursive: false }],
  // Ollama writes PDFs in output/ and HTML under output/ollama-html/ — need recursive watch to refresh the UI
  ['output', PATHS.output, { recursive: true }],
  ['reports', PATHS.reports, { recursive: false }],
]) {
  if (existsSync(path)) {
    try {
      watch(path, opts, () => broadcastUpdate(kind));
    } catch {
      watch(path, { recursive: false }, () => broadcastUpdate(kind));
    }
  }
}

app.listen(PORT, () => {
  console.log('╔══════════════════════════════════════╗');
  console.log('║   AI Job Hunt Dashboard              ║');
  console.log('║   http://localhost:3000              ║');
  console.log('║   Namratha Murarikar — ML Engineer   ║');
  console.log('╚══════════════════════════════════════╝');
});
